language: android
android:
  components:
    - tools
    - android-23
    - build-tools-23.0.2

before_install:
  - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - ./gradlew clean test